language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "stable"
  - "iojs"
matrix:
  allow_failures:
    - node_js: "0.8"
    - node_js: "0.10"
    - node_js: "0.12"
sudo: false
